<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>latest</LangVersion>
    <AssemblyName>yongbongE</AssemblyName>
    <RootNamespace>TinyFtpDrive</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="winfsp.net" Version="2.2.26215" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Security" />
  </ItemGroup>
</Project>
